== Koncepty

Formát popisuje sady předdefinovaných poloh – úseků silniční sítě, na které odkazují zprávy jiných formátů.
Odkazující zpráva nese jen identifikátor a verzi polohy; úplný popis polohy je v této publikaci.

Sada obsahuje polohy jednoho druhu, například:

* úseky FCD – úseky mezi lokacemi ALERT-C, každý směr jízdy jako samostatná poloha,
* úseky meteohlásek – úseky silnice u meteohlásek, platné pro oba směry jízdy.

Formát vychází z publikace `loc:PredefinedLocationsPublication`
<<EN16157-2>>.

[[obalka]]
=== Obálka a hlavička publikace

Zpráva je dokument DATEX II 3 s kořenovým elementem `d2:payload` typu `loc:PredefinedLocationsPublication`.
Formát identifikují atributy kořene `@profileName` (`cz-ndic_d2-pls`) a `@profileVersion` (`2.0`).

Hlavička obsahuje:

* `feedType` – identifikátor zdroje dat (distribuce) v registru národního přístupového bodu <<nap>>; formát zprávy určují atributy
  `@profileName` a `@profileVersion`, nikoli `feedType`; element `feedDescription` se nepoužívá,
* `publicationTime` – čas vygenerování publikace; mění se s každým vygenerováním, i když se obsah nezměnil,
* `publicationCreator` – `cz` a `NDIC`,
* `headerInformation` – vždy:
** `confidentiality` = `noRestriction`,
** `informationStatus` = `real`.

.Kořenový element a hlavička publikace (vzorek `predefined_location_set-fcd.xml`)
[source,xml]
----
include::{samplesdir}/predefined_location_set-fcd.xml[lines=2]
include::{samplesdir}/predefined_location_set-fcd.xml[tag=header,indent=2]
  ...
----

[[predef]]
=== Předdefinované polohy

Každá poloha sady je element `predefinedLocationReference`. Jeho typ určuje, jak poloha vede:

[cols="2,3",options="header"]
|===
|Typ |Poloha
|`loc:PredefinedLocation` |souvislý úsek jedné komunikace (<<jedna-komunikace>>)
|`loc:PredefinedItinerary` |trasa – souvislá poloha přes více komunikací (<<trasy>>)
|`loc:PredefinedLocationGroup` |nesouvislá skupina poloh, např. oblast (<<skupiny>>)
|===

*Pravidlo jedné komunikace.* Popis polohy (`location`) je vždy liniová poloha
`loc:SingleRoadLinearLocation` – souvislý úsek jedné silnice nebo ulice, jehož všechny metody popisu
(<<polohy>>) mají stejný rozsah. Platí to pro samostatnou polohu i pro každou část trasy a skupiny:

* Novou část nezakládá úsek jiné komunikace uvnitř křižovatky, krátká spojka ani souběh dvou silnic.
* Má-li poloha popis ALERT-C, odpovídá jedné cestě lokační tabulky ALERT-C.

*Společné vlastnosti.*

* *Identifikátor* (`@id`) je stálý. Úseky FCD ho mají složený z lokací ALERT-C: `TS02125T15781` je úsek
  z lokace 2125 do lokace 15781 (čísla lokací doplněná nulami na pět číslic), opačný směr je `TS15781T02125`.
* *Název* (`predefinedLocationName`) se uvádí, jen má-li ho poloha ve zdroji: úseky meteohlásek mají název
  meteohlásky (`I/43 Černá Hora`, `D0 15.742`), úseky FCD, trasy a skupiny název nemají.
* *Verze* (`@version`) odpovídá vydání sítě Global Network, ze kterého je sada odvozena, ve tvaru
  `RRMM01` (síť 25.06 → `250601`):
** s každým vydáním sítě dostanou novou verzi *všechny* polohy sady, i ty, u nichž se změnilo jen označení
   verze sítě (`linearElementReferenceModelVersion`); identifikátor zůstává,
** nová poloha dostává nový identifikátor,
** zprávy odkazují vždy na verzi z aktuální sady.
* Publikace vždy obsahuje všechny platné polohy, i ty dříve vydané. Uvnitř poloh se žádný čas neuvádí.

*Části trasy a skupiny.*

. Trasa i skupina mají vlastní identifikátor a verzi; název se neuvádí.
. Každá část je vnořený element `predefinedLocation` – úplná předdefinovaná poloha s vlastním
  identifikátorem, verzí, popisem polohy a případně názvem (stejně jako samostatná poloha).
. Trasa i skupina mají nejméně dvě části.
. Identifikátory částí jsou jedinečné v celé publikaci; tatáž část se v trase, ve skupině ani v publikaci
  neopakuje.
. Změní-li se část, dostane novou verzi ona i celá trasa nebo skupina; přidání nebo odebrání části mění verzi
  trasy nebo skupiny.

[[jedna-komunikace]]
==== Poloha na jedné komunikaci

Poloha na jedné komunikaci je element `predefinedLocationReference` typu `loc:PredefinedLocation`; její
`location` je `loc:SingleRoadLinearLocation`.

.Poloha na jedné komunikaci
image::jedna-komunikace.svg[Poloha na jedné komunikaci,width=640,align="center"]

.Předdefinovaná poloha – úsek meteohlásky popsaný OpenLR, ALERT-C a úseky GN (vzorek `predefined_location_set-weather.xml`)
[source,xml]
----
include::{samplesdir}/predefined_location_set-weather.xml[tag=weather-1,indent=0]
----

[[trasy]]
==== Trasa přes více komunikací

Souvislá poloha, která vede z jedné komunikace na jinou (např. stálá objízdná trasa po silnici II. třídy
a navazující silnici III. třídy), je trasa – element `predefinedLocationReference` typu
`loc:PredefinedItinerary`. Je to souvislá skupina poloh: každá její část leží na jedné komunikaci.

.Trasa přes dvě komunikace
image::trasa.svg[Trasa přes více komunikací,width=640,align="center"]

* Části jsou v pořadí jízdy (u obousměrné polohy v pořadí prvního směru); konec části je počátkem
  následující a části se nepřekrývají.
* Směrovost je ve všech částech shodná; každá část má vlastní průběh `gmlLineString`.

Zápis odpovídá trase přes více komunikací ve formátech událostí, kde jsou části očíslované atributem
`@index`; v sadě poloh určuje pořadí částí jejich pořadí v trase.

.Trasa po dvou silnicích (vzorek `predefined_location_itinerary.xml`, zkráceno)
[source,xml]
----
include::{samplesdir}/predefined_location_itinerary.xml[tag=itinerary-head,indent=0]
      ...
    </loc:predefinedLocation>
include::{samplesdir}/predefined_location_itinerary.xml[tag=itinerary-part-2,indent=2]
      ...
    </loc:predefinedLocation>
  </loc:predefinedLocationReference>
----

[[skupiny]]
==== Nesouvislá skupina poloh

Nesouvislá skupina sdružuje úseky, na které se opakovaně odkazuje jako na celek a které na sebe nenavazují
– i na různých silnicích: oblast pravidelných zimních uzavírek, úseky v okolí meteohlásky. Je to element
`predefinedLocationReference` typu `loc:PredefinedLocationGroup`.

.Skupina tří nesouvislých úseků na dvou silnicích
image::skupina-poloh.svg[Skupina poloh – nesouvislé úseky,width=640,align="center"]

* Pořadí částí ve skupině nemá význam.
* Zpráva odkazuje na celou skupinu typem `loc:LocationGroupByReference` (`@targetClass` =
  `loc:PredefinedLocationGroup`).
* Předdefinované skupiny se zakládají jen pro oblasti, které se opakují; jednorázové oblastní jevy popisují
  formáty událostí skupinou úseků přímo ve zprávě.

.Skupina poloh (vzorek `predefined_location_loc_group.xml`, zkráceno)
[source,xml]
----
include::{samplesdir}/predefined_location_loc_group.xml[tag=group-head,indent=0]
    ...
  </loc:predefinedLocation>
  <loc:predefinedLocation id="…" version="…">
    ...
  </loc:predefinedLocation>
</loc:predefinedLocationReference>
----

[[smer]]
=== Směr a obousměrné polohy

Poloha je buď jednosměrná, nebo platí pro oba směry jízdy:

* *Úseky FCD* jsou jednosměrné; každý směr je samostatná poloha (`TS02125T15781`, `TS15781T02125`).
* *Úseky meteohlásek* a další obousměrné polohy popisuje *jedna* poloha pro oba směry. Každá metoda
  vyjadřuje obousměrnost po svém:

[cols="1,4",options="header"]
|===
|Metoda |Obousměrná poloha
|ALERT-C |`alertCAffectedDirection` = `both` (jednosměrná `aligned`)
|OpenLR |`firstDirection` pro směr polohy a `oppositeDirection` pro protisměr – každý s vlastními
referenčními body a ofsety; není-li protisměr zakódován, viz <<openlr>>
|Global Network |úseky společné oběma směrům jednou s `directionRelativeOnLinearSection` = `both`; vede-li
protisměr jinudy (oddělené jízdní pásy, jednosměrné úseky), následuje za trasou prvního směru celá trasa
protisměru (<<gn>>)
|===

Skupina poloh se pro obousměrnost nepoužívá. Dvojice jednosměrných poloh sdružená do skupiny by
vyžadovala odkaz jiného typu (`loc:LocationGroupByReference`), ztratila by vazbu mezi směry a metody
OpenLR a ALERT-C by obousměrnost vyjadřovaly dvakrát. Skupina je vyhrazena pro oblasti.

[[polohy]]
== Popisování poloh

Poloha je liniová (`loc:SingleRoadLinearLocation`) – vždy souvislý úsek jedné komunikace – a bývá popsána několika metodami podle jejich
dostupnosti; všechny popisují tentýž úsek a alespoň jedna musí být uvedena. Úseky FCD i meteohlásek jsou
popsány alespoň jednou metodou; průběh polohy se uvádí, obsahuje-li poloha úseky GN.

Fyzicky bodové místo – meteohláska, most, vjezd do tunelu – se popisuje jako krátký úsek komunikace,
na kterém leží, a to ve všech metodách stejně: v ALERT-C úsek mezi dvěma lokacemi, případně se shodnou
primární a sekundární lokací; v OpenLR a v síti GN úsek nenulové délky v okolí místa (OpenLR úsek nulové
délky nepřipouští). Bodové polohy (`loc:PointLocation`) sady poloh nepoužívají.

[cols="2,3,3",options="header"]
|===
|Metoda |Element |Pro koho
|ALERT-C |`alertCLinear` |navigace s lokační tabulkou RDS-TMC
|OpenLR |`openlrLinear` |napojení na libovolnou mapu
|Global Network |`linearWithinLinearElement` (`loc:LinearElementByCode`) |uživatelé sítě GN
|Průběh polohy |`gmlLineString`, `coordinatesForDisplay` |zobrazení v mapě bez dalších podkladů (<<prubeh>>)
|Staničení |`linearWithinLinearElement` s `roadNumber` |sady NDIC ho neobsahují (nepovinné)
|===

[[alertc]]
=== Popis polohy pomocí ALERT-C

include::{kitdir}/shared/cs/poloha/alertc.adoc[]

.Popis polohy pomocí ALERT-C – směr, sekundární a primární lokace
image::alertc-poloha.svg[ALERT-C – směr a lokace,width=680,align="center"]

.Popis polohy pomocí ALERT-C (vzorek `predefined_location_set-weather.xml`)
[source,xml]
----
include::{samplesdir}/predefined_location_set-weather.xml[tag=loc-alertc,indent=0]
----

[[openlr]]
=== Popis polohy pomocí OpenLR

include::{kitdir}/shared/cs/poloha/openlr.adoc[]

.Obousměrná poloha v OpenLR na komunikaci s oddělenými pásy
image::openlr-obousmerne.svg[OpenLR – firstDirection a oppositeDirection,width=680,align="center"]

.Obousměrná poloha v OpenLR (vzorek `predefined_location_both-directions.xml`)
[source,xml]
----
include::{samplesdir}/predefined_location_both-directions.xml[tag=openlr-both,indent=0]
----

[[staniceni]]
=== Popis polohy pomocí staničení

NOTE: Staničení je součástí profilu; sady poloh NDIC ho neobsahují – odběratel s ním má počítat jako s nepovinným.

include::{kitdir}/shared/cs/poloha/staniceni.adoc[]

[[gn]]
=== Popis polohy pomocí sítě Global Network

include::{kitdir}/shared/cs/poloha/gn.adoc[]

.Poloha v jednom směru složená z úseků GN
image::gn-poloha.svg[GN – složení polohy z úseků,width=680,align="center"]

==== Obousměrná poloha v síti GN

.Obousměrná poloha v síti GN – společné úseky a oddělené jízdní pásy
image::gn-obousmerne.svg[GN – obousměrná poloha,width=680,align="center"]

include::{kitdir}/shared/cs/poloha/gn-obousmerne-spolecne.adoc[]

.Úseky Global Network – úseky společné oběma směrům (vzorek `predefined_location_both-directions.xml`)
[source,xml]
----
include::{samplesdir}/predefined_location_both-directions.xml[tag=gn-both,indent=0]
----

První úsek (3663224) vede od 30,47{nbsp}% k 0{nbsp}% a poslední úsek (901099) od 100{nbsp}% k 12,58{nbsp}%; první směr tedy na obou vede proti směru kódování. Celé vnitřní úseky 1327329 a
1326918 vede první směr také proti směru kódování (100 → 0).

include::{kitdir}/shared/cs/poloha/gn-obousmerne-oddelene.adoc[]

V ukázce jsou všechny úseky obou tras jednosměrné (`aligned`).

.Úseky Global Network – oddělené jízdní pásy (vzorek `predefined_location_both-directions.xml`)
[source,xml]
----
include::{samplesdir}/predefined_location_both-directions.xml[tag=gn-separate,indent=0]
----

[[prubeh]]
=== Průběh polohy

include::{kitdir}/shared/cs/poloha/prubeh.adoc[]

V sadě poloh nese poloha navíc `coordinatesForDisplay` – bod pro značku v mapě, střed linie.

.Průběh polohy (vzorek `predefined_location_set-weather.xml`)
[source,xml]
----
include::{samplesdir}/predefined_location_set-weather.xml[tag=loc-gml,indent=0]
----
